### ISSUE TITLE
impulseDE2.R

### ISSUE THREAD

**Issue by wyim-pgl** [daniel-spies/rna-seq_tcComp#1]
Dear Daniel,

Hello, thank you for the nice review.
I am trying to reproduce the data with impulseDE2.R.
Do you have example running data such as  xM_yrep_zTP_contr.txt ?

Thank you so much.

Won

**Comment by daniel-spies** [comment]
dear Won,

thanks so much for your interest, the simulation files were merged into a single one (review process, was not my choice) into the file “Simulation_data_Spies_et_al.txt”.
But as the papers now out I will put back the single files for easier access. 

cheers
Daniel

**Comment by wyim-pgl** [comment]
I got it.
I think it will work.

Thank you.

Won

=============

Won Cheol Yim

Postdoctoral Researcher

+1 775 229 0453 | wyim@unr.edu<mailto:wyim@unr.edu> | https://sites.google.com/site/ascendou<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsites.google.com%2Fsite%2Fascendou&data=01%7C01%7Cwyim%40unr.edu%7C8df78f00ccc84f6d866f08d4c87dab75%7C523b4bfc0ebd4c03b2b96f6a17fd31d8%7C1&sdata=PPCtqdvmkT1ljqTfOyqviuSDAJbvpAmNv78i3LC7xaM%3D&reserved=0>

MS330/Department of Biochemistry & Molecular Biology
1664 N. Virginia Street, Reno NV
University of Nevada - Reno
89557

**Comment by wyim-pgl** [comment]
It worked thanks.!

**Comment by daniel-spies** [comment]
you’re very welcome!

cheers
daniel
