### ISSUE TITLE
Biological data file

### ISSUE THREAD

**Issue by koenvandenberge** [daniel-spies/rna-seq_tcComp#2]
Dear,

Thank you for providing this GitHub repository together with your interesting manuscript.
I was wondering whether you could provide some additional information on your `Biological_data_Kiselov_et al.txt` file in your repository; does this file contain the real dataset from Kiselov _et al._ or rather simulated data? 
There seems to be three cell types in the file; PIK3CA, PTEN knockout and wild type. For each cell type, there are raw and normalized counts, each for a treatment and control condition. What does the treatment relate to? 
In the biological paper and corresponding GEO accession, it seems like no specific control and treatment conditions are described.

Best,
Koen

**Comment by daniel-spies** [comment]
Dear Koen,


the data supplied is processed data from the Kiselev et al paper.

You’re correct, this paper looked at three conditions: WT, single allele PIK3CA-H1047R (catalytic subunit) mutant and a PTEN-KO upon EGF stimulation

whereas for the long-term (chronic) effects they compared 
	-PIK3CA_mut vs WT 
	-PTEN_KO vs WT 

and for short term effects they looked at 
	- WT vs WT+PIK3CA inhibitor A66

for the simulation we focused on the comparison of the chronic mutants time course plus the chronic mutant DE without EGF stimulation (t=0),
so here to run the tools I the pen/pik3ca control files are in fact the WT non-stimulated samples, whereas the WT control time course was assumed to be flat and was therefore sampled from the non-stimulated WT T=0 

the normalised data represents edgeR cpm normalised counts taking into account the sample groups (WT,PIK3CA,PTEN)


let me know if you need anything else

cheers
Daniel

**Comment by koenvandenberge** [comment]
Dear Daniel,

Thank you for your swift response.
I was rather aiming to find out what the headers in the file specifically mean. 
For example, in the `Biological_data_Kiselov_et al.txt` file, we have headers `30M_3rep_6TP_GSE69822_pik3ca_contr`, referring to a control condition of PIK3CA, over 6 timepoints with 3 replicates for each timepoint. Similar, there is a header called `30M_3rep_6TP_GSE69822_pik3ca_treat`, but what is this specific biological treatment? 
Could you point me to what is meant by 'treatment' in your file based on the original paper?

Best,
Koen

**Comment by daniel-spies** [comment]
dear Koen,

all samples in this paper were stimulated / treated with EGF (except some A66 samples which I did not use anyways)
I simply created for each condition treatment/control files to more easily automatise the process. 

30M_3rep_6TP_GSE69822_pik3ca_treat = pik3ca mutant stimulated with EGF
30M_3rep_6TP_GSE69822_pik3ca_contr= WT stimulated with EGF

30M_3rep_6TP_GSE69822_pten_treat= pten mutant stimulated with EGF
30M_3rep_6TP_GSE69822_pten_contr= WT stimulated with EGF

30M_3rep_6TP_GSE69822_wt_treat= WT stimulated with EGF
30M_3rep_6TP_GSE69822_wt_contr= WT without stimulation ( re-sampling of T=0)

best
Daniel

**Comment by koenvandenberge** [comment]
Ok, great, many thanks!

**Comment by daniel-spies** [comment]
welcome!

all the best
Daniel Spies

ETH Zurich
Institute of Molecular Health Sciences
Department of Biology
HPL G28
Otto-Stern-Weg 7
CH-8093 Zurich

Phone: +41 44 633 08 81
Email: daniel.spies@biol.ethz.ch<mailto:daniel.spies@biol.ethz.ch>










On 19 Jun 2019, at 14:37, Koen Van den Berge <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, great, many thanks!
